name: Dependency review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  license_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, BSD-3-Clause, GPL-3.0
          comment-summary-in-pr: always
