name: build pull request

on:
   pull_request:
     types:
       - opened
       - reopened
       - edited

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'gradle'
            - name: Test & build
              run: ./gradlew test build
